apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/notmatthewa/ArgoLocks.git
    targetRevision: main
    path: k8s/sample-app
  destination:
    server: https://kubernetes.default.svc
    namespace: sample-app-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
